<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>XkScreenshot.Translate</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.27.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\XkScreenshot.Core\XkScreenshot.Core.csproj" />
  </ItemGroup>

</Project>
